/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/nN4US6ztYv0
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Manrope } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

manrope({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Slider } from "@/components/ui/slider"

export function Component() {
  return (
    <div className="flex min-h-screen">
      <aside className="bg-[#282828] text-white w-64 p-6 flex flex-col">
        <div className="flex items-center gap-2 mb-6">
          <AirplayIcon className="w-8 h-8" />
          <span className="text-2xl font-bold">Spotify</span>
        </div>
        <nav className="flex-1 space-y-4">
          <Link href="#" className="flex items-center gap-2 hover:text-[#1DB954]" prefetch={false}>
            <HomeIcon className="w-5 h-5" />
            <span>Home</span>
          </Link>
          <Link href="#" className="flex items-center gap-2 hover:text-[#1DB954]" prefetch={false}>
            <SearchIcon className="w-5 h-5" />
            <span>Search</span>
          </Link>
          <Link href="#" className="flex items-center gap-2 hover:text-[#1DB954]" prefetch={false}>
            <LibraryIcon className="w-5 h-5" />
            <span>Your Library</span>
          </Link>
          <div className="border-t border-[#3E3E3E] pt-4">
            <Link href="#" className="flex items-center gap-2 hover:text-[#1DB954]" prefetch={false}>
              <PlusIcon className="w-5 h-5" />
              <span>Create Playlist</span>
            </Link>
            <Link href="#" className="flex items-center gap-2 hover:text-[#1DB954] mt-2" prefetch={false}>
              <HeartIcon className="w-5 h-5" />
              <span>Liked Songs</span>
            </Link>
          </div>
        </nav>
        <div className="border-t border-[#3E3E3E] pt-4 text-[#B3B3B3] text-sm">
          <p className="truncate">Playlist Name</p>
          <ul className="mt-2 space-y-2">
            <li className="flex items-center gap-2 text-[#1DB954] font-bold">
              <Music2Icon className="w-5 h-5" />
              <span>Song Name</span>
            </li>
            <li className="flex items-center gap-2 hover:text-[#1DB954]">
              <Music2Icon className="w-5 h-5" />
              <span>Song Name</span>
            </li>
            <li className="flex items-center gap-2 hover:text-[#1DB954]">
              <Music2Icon className="w-5 h-5" />
              <span>Song Name</span>
            </li>
            <li className="flex items-center gap-2 hover:text-[#1DB954]">
              <Music2Icon className="w-5 h-5" />
              <span>Song Name</span>
            </li>
          </ul>
        </div>
      </aside>
      <div className="flex flex-col flex-1">
        <header className="bg-[#1DB954] text-white px-6 py-4 flex items-center justify-between">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <AirplayIcon className="w-8 h-8" />
            <span className="text-2xl font-bold">Spotify</span>
          </Link>
          <nav className="flex items-center gap-6">
            <Link href="#" className="hover:underline" prefetch={false}>
              Premium
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Support
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Download
            </Link>
            <div className="h-6 w-[1px] bg-white/50" />
            <Link href="#" className="hover:underline" prefetch={false}>
              Sign Up
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Log In
            </Link>
          </nav>
        </header>
        <main className="flex-1 bg-[#121212] text-white">
          <div className="container mx-auto py-8 px-6">
            <div className="mb-8">
              <Input
                type="search"
                placeholder="Search for artists, songs, or podcasts"
                className="w-full rounded-full bg-[#282828] px-4 py-2 text-white focus:outline-none"
              />
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              <div className="bg-[#282828] rounded-lg overflow-hidden cursor-pointer hover:bg-[#3E3E3E] transition-colors">
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={200}
                  alt="Album Cover"
                  className="w-full h-48 object-cover"
                  style={{ aspectRatio: "200/200", objectFit: "cover" }}
                />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">Album Name</h3>
                  <p className="text-sm text-[#B3B3B3]">Artist Name</p>
                </div>
              </div>
              <div className="bg-[#282828] rounded-lg overflow-hidden cursor-pointer hover:bg-[#3E3E3E] transition-colors">
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={200}
                  alt="Album Cover"
                  className="w-full h-48 object-cover"
                  style={{ aspectRatio: "200/200", objectFit: "cover" }}
                />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">Album Name</h3>
                  <p className="text-sm text-[#B3B3B3]">Artist Name</p>
                </div>
              </div>
              <div className="bg-[#282828] rounded-lg overflow-hidden cursor-pointer hover:bg-[#3E3E3E] transition-colors">
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={200}
                  alt="Album Cover"
                  className="w-full h-48 object-cover"
                  style={{ aspectRatio: "200/200", objectFit: "cover" }}
                />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">Album Name</h3>
                  <p className="text-sm text-[#B3B3B3]">Artist Name</p>
                </div>
              </div>
              <div className="bg-[#282828] rounded-lg overflow-hidden cursor-pointer hover:bg-[#3E3E3E] transition-colors">
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={200}
                  alt="Album Cover"
                  className="w-full h-48 object-cover"
                  style={{ aspectRatio: "200/200", objectFit: "cover" }}
                />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">Album Name</h3>
                  <p className="text-sm text-[#B3B3B3]">Artist Name</p>
                </div>
              </div>
            </div>
          </div>
        </main>
        <footer className="bg-[#181818] text-[#B3B3B3] px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <img
              src="/placeholder.svg"
              width={64}
              height={64}
              alt="Album Cover"
              className="w-12 h-12 rounded"
              style={{ aspectRatio: "64/64", objectFit: "cover" }}
            />
            <div>
              <h3 className="text-white font-bold">Song Name</h3>
              <p>Artist Name</p>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <Button variant="ghost" size="icon">
              <ShuffleIcon className="w-5 h-5" />
            </Button>
            <Button variant="ghost" size="icon">
              <SkipBackIcon className="w-5 h-5" />
            </Button>
            <Button variant="ghost" size="icon">
              <PlayIcon className="w-5 h-5" />
            </Button>
            <Button variant="ghost" size="icon">
              <SkipForwardIcon className="w-5 h-5" />
            </Button>
            <Button variant="ghost" size="icon">
              <RepeatIcon className="w-5 h-5" />
            </Button>
            <Slider
              className="w-40 [&>span:first-child]:h-1 [&>span:first-child]:bg-white/30 [&_[role=slider]]:bg-white [&_[role=slider]]:w-3 [&_[role=slider]]:h-3 [&_[role=slider]]:border-0 [&>span:first-child_span]:bg-white [&_[role=slider]:focus-visible]:ring-0 [&_[role=slider]:focus-visible]:ring-offset-0 [&_[role=slider]:focus-visible]:scale-105 [&_[role=slider]:focus-visible]:transition-transform"
              defaultValue={[40]}
            />
            <Button variant="ghost" size="icon">
              <Volume2Icon className="w-5 h-5" />
            </Button>
          </div>
        </footer>
      </div>
    </div>
  )
}

function AirplayIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 17H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-1" />
      <path d="m12 15 5 6H7Z" />
    </svg>
  )
}


function HeartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
    </svg>
  )
}


function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function LibraryIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m16 6 4 14" />
      <path d="M12 6v14" />
      <path d="M8 8v12" />
      <path d="M4 4v16" />
    </svg>
  )
}


function Music2Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="18" r="4" />
      <path d="M12 18V2l7 4" />
    </svg>
  )
}


function PlayIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="6 3 20 12 6 21 6 3" />
    </svg>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function RepeatIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m17 2 4 4-4 4" />
      <path d="M3 11v-1a4 4 0 0 1 4-4h14" />
      <path d="m7 22-4-4 4-4" />
      <path d="M21 13v1a4 4 0 0 1-4 4H3" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function ShuffleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 18h1.4c1.3 0 2.5-.6 3.3-1.7l6.1-8.6c.7-1.1 2-1.7 3.3-1.7H22" />
      <path d="m18 2 4 4-4 4" />
      <path d="M2 6h1.9c1.5 0 2.9.9 3.6 2.2" />
      <path d="M22 18h-5.9c-1.3 0-2.6-.7-3.3-1.8l-.5-.8" />
      <path d="m18 14 4 4-4 4" />
    </svg>
  )
}


function SkipBackIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="19 20 9 12 19 4 19 20" />
      <line x1="5" x2="5" y1="19" y2="5" />
    </svg>
  )
}


function SkipForwardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="5 4 15 12 5 20 5 4" />
      <line x1="19" x2="19" y1="5" y2="19" />
    </svg>
  )
}


function Volume2Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5" />
      <path d="M15.54 8.46a5 5 0 0 1 0 7.07" />
      <path d="M19.07 4.93a10 10 0 0 1 0 14.14" />
    </svg>
  )
}
